### ISSUE TITLE
Error when launching Slicer after installing TOMAAT

### ISSUE THREAD

**Issue by adamrankin** [faustomilletari/TOMAAT-Slicer#13]
I receive the following error after installing the TOMAAT extension.

```
Could not install packages due to an EnvironmentError: [Error 5] Access is denied: 'C:\\Program Files\\Slicer 4.11.0-2019-02-19\\lib\\Python\\Lib\\site-packages\\requests_toolbelt'
Consider using the `--user` option or check the permissions.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/Users/arankin/AppData/Roaming/NA-MIC/Extensions-27968/TOMAAT/lib/Slicer-4.11/qt-scripted-modules/TOMAAT.py", line 1, in <module>
    import utils.dependencies
  File "C:\Users\arankin\AppData\Roaming\NA-MIC\Extensions-27968\TOMAAT\lib\Slicer-4.11\qt-scripted-modules\utils\dependencies.py", line 20, in <module>
    from requests_toolbelt import MultipartEncoder, MultipartEncoderMonitor
ImportError: No module named requests_toolbelt
SystemError: D:\D\P\Slicer-0-build\Python-2.7.13\Objects\classobject.c:521: bad argument to internal function
```

Can the missing dependency be packaged with the extension?

**Comment by adamrankin** [comment]
After retrying Slicer in administrator mode (to get write permissions), I get 
```
Collecting requests_toolbelt
  Using cached https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl
Requirement already satisfied: requests<3.0.0,>=2.0.1 in c:\program files\slicer 4.11.0-2019-02-19\lib\python\lib\site-packages (from requests_toolbelt) (2.21.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\program files\slicer 4.11.0-2019-02-19\lib\python\lib\site-packages (from requests<3.0.0,>=2.0.1->requests_toolbelt) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\program files\slicer 4.11.0-2019-02-19\lib\python\lib\site-packages (from requests<3.0.0,>=2.0.1->requests_toolbelt) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\program files\slicer 4.11.0-2019-02-19\lib\python\lib\site-packages (from requests<3.0.0,>=2.0.1->requests_toolbelt) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\slicer 4.11.0-2019-02-19\lib\python\lib\site-packages (from requests<3.0.0,>=2.0.1->requests_toolbelt) (2018.11.29)
Installing collected packages: requests-toolbelt
Successfully installed requests-toolbelt-0.9.1
SystemError: D:\D\P\Slicer-0-build\Python-2.7.13\Objects\classobject.c:521: bad argument to internal function
```

**Comment by adamrankin** [comment]
However, the TOMAAT module seems to work, as I am able to see services.

**Comment by j-frei** [comment]
It seems that the file TOMAAT/__init__.py confuses Slicer when the widget is processed...
